### ISSUE TITLE
[ask]how to add proxy username and password?

### ISSUE THREAD

**Issue by DzT13** [MatrixTM/OutlookGen#1]
hii i've proxy with username and password, how to pass it to software? icant find any clue thanks!

**Comment by DzT13** [comment]
hi i can pass the username and password.

here the solution
IP:PORT:USERNAME:PWD

thanks!

**Comment by LoshyLoshy** [comment]
This doesn't work for me? I'm getting invalid proxy @BlackSnowDot

**Comment by BlackSnowDot** [comment]
what is your proxy type?
