### ISSUE TITLE
Something is wrong

### ISSUE THREAD

**Issue by g3nesis059** [MatrixTM/OutlookGen#12]
Is there a log file to tell me what's wrong?

**Comment by BlackSnowDot** [comment]
Give me ten minutes; I'll fix it.

**Comment by g3nesis059** [comment]
Ok, very quick to respond! given the time, I will resume tomorrow! Thank you see you tomorrow !

**Comment by BlackSnowDot** [comment]
## Script is working and only thing you need is a good proxy
![image](https://user-images.githubusercontent.com/95581741/203447651-5d899dcb-c832-424b-8f91-056cf0ad2f93.png)
![image](https://user-images.githubusercontent.com/95581741/203447888-5be5afe6-f5bc-421e-a79c-0f07501ad2a5.png)

**Comment by BlackSnowDot** [comment]
## Another image
![image](https://user-images.githubusercontent.com/95581741/203448256-18432f40-a648-4ab6-901e-43ddd1a76d13.png)

**Comment by g3nesis059** [comment]
![Capture d’écran 2022-11-23 014739](https://user-images.githubusercontent.com/48258831/203449417-2d2adc2d-83c3-45c5-867a-2024a4616e65.jpg)

My proxies are residential rotating proxies. I can use them to create accounts manually without any problems. I also tried fixed ip residential proxies. type: 176.116.236.238 this one is German. I tried with Poles too. Maybe I'm doing something wrong?

**Comment by BlackSnowDot** [comment]
Update Script

**Comment by g3nesis059** [comment]
![Capture d’écran 2022-11-23 215527](https://user-images.githubusercontent.com/48258831/203644493-533d329e-3914-4d6e-bf08-a11e396627f8.jpg)

**Comment by g3nesis059** [comment]
![Capture d’écran 2022-11-23 215640](https://user-images.githubusercontent.com/48258831/203644654-21f5f3e5-5eb0-473b-b257-b560a837ec74.jpg)

**Comment by g3nesis059** [comment]
if i use proxy with id & passwd. this format is ok ? IP:PORT:Username:pass

**Comment by BlackSnowDot** [comment]
i think its okay

**Comment by BlackSnowDot** [comment]
Check [This](https://github.com/MatrixTM/OutlookGen/issues/1#issuecomment-1264451237) issues
