### ISSUE TITLE
not running

### ISSUE THREAD

**Issue by Misterpopcorn12** [MatrixTM/OutlookGen#13]
when i run the script nothing happends
![Screenshot_18](https://user-images.githubusercontent.com/83051550/204083705-4ff4ae9d-f665-4aaa-9332-c6c0260a1508.png)

**Comment by BlackSnowDot** [comment]
What is your OS?

**Comment by Misterpopcorn12** [comment]
windows 10 x64

**Comment by BlackSnowDot** [comment]
download script and try again

**Comment by Misterpopcorn12** [comment]
nope still not working now it says colorama is not installed even tho when i try to install it it says its installed

**Comment by BlackSnowDot** [comment]
try without "python3"
only main.py
