### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by DimZZyPlays1** [MatrixTM/OutlookGen#14]
![image](https://user-images.githubusercontent.com/83815671/204279581-dc889b4e-6153-42eb-98a3-33aa19bbbd2a.png)
How do i fix this?
Indexerror: list index out of range

**Comment by Yoko11111111** [comment]
you cant the code is not working

> ![image](https://user-images.githubusercontent.com/83815671/204279581-dc889b4e-6153-42eb-98a3-33aa19bbbd2a.png) How do i fix this? Indexerror: list index out of range

**Comment by BlackSnowDot** [comment]
no proxy error
