### ISSUE TITLE
2 Captcha bug dont work

### ISSUE THREAD

**Issue by Yoko11111111** [MatrixTM/OutlookGen#18]
![grafik](https://user-images.githubusercontent.com/108374464/206105211-7bd045fb-64a0-43fc-9d19-a8e6173afe68.png)

**Comment by JIK-Dev** [comment]
pip install 2captcha-python,
they wrote the wrong package in the requirements

**Comment by Yoko11111111** [comment]
> pip install 2captcha-python, they wrote the wrong package in the requirements

k thx
