### ISSUE TITLE
2captcha wont solve the captcha

### ISSUE THREAD

**Issue by DzT13** [MatrixTM/OutlookGen#2]
hi, i think captcha didnt solve, first its error occured, then i try non headless. when come to enter captcha, the captcha wont solve, any idea how to fix it ?

**Comment by BlackSnowDot** [comment]
What error does it give in console?

**Comment by DzT13** [comment]
first it says 

"tried 100 time to find element..."
then 
"Something is wrong :("

looping again from start then infinite loop says
"tried 100 time to find element..."
"Something is wrong :("

**Comment by BlackSnowDot** [comment]
if its after printing email and password
problem is your proxy
use better proxy

**Comment by DzT13** [comment]
so not the captcha solver ?
im using 2captcha provider
any sugestion for proxy ?

**Comment by BlackSnowDot** [comment]
http://www.proxydocker.com/
Google Bot Proxy

**Comment by DzT13** [comment]
i got working proxy but got error looping like this

`PS C:\OutlookGen> py .\main.py
Loading Arguments | Loading Arguments: 100%|███████████████ | 100%
eGen>> Coded with <3 by MatrixTeam
eGen>> 4.228.96.160:3128:x:x
eGen>> email: SuCiTiffie414@outlook.com
eGen>> Password: D4EE75F495
eGen>> tried 100 time to find element...
eGen>> Something is wrong :(
eGen>> 4.228.96.160:3128x:x
eGen>> email: HermiBaFlutteriBg@outlook.com
eGen>> Password: C107EB3BA7
eGen>> tried 100 time to find element...
eGen>> Something is wrong :(
eGen>> 4.228.96.160:3128:x:x
eGen>> email: HannyLandocalrissianB28@outlook.com
eGen>> Password: E780851C00
eGen>> tried 100 time to find element...
eGen>> Something is wrong :(
eGen>> 4.228.96.160:3128:x:x
eGen>> email: KaceCTamil365@outlook.com
eGen>> Password: AA695CD3E1
`

im using 2captcha provider btw
i just have 1 working proxy

**Comment by BlackSnowDot** [comment]
when u see "tried 100 time to find element..." after print password
u are in number verify page

**Comment by BlackSnowDot** [comment]
and you are in number verify page because ur proxy is bad

**Comment by DzT13** [comment]
ouch
so my proxy is bad?
btw can i reach u on telegram?

**Comment by BlackSnowDot** [comment]
yes ur proxies is bad
for telegram [click here](https://t.me/BlackSnowDot)
