### ISSUE TITLE
Hello 👋 

### ISSUE THREAD

**Issue by JokersCat** [MatrixTM/OutlookGen#4]
So I just wanted to know how you found the code to submit the funcaptcha token to the website I was searching for hours to find something in the web but found nothing how did you find it? 🧐

PS: I don’t testet the code since yet but it looks pretty legit so I would give it a try if you say that this is still working.

**Comment by BlackSnowDot** [comment]
https://user-images.githubusercontent.com/95581741/194816260-8b5d45b4-5212-4197-bff6-1ceef7c78be4.mp4
