### ISSUE TITLE
Proxy error

### ISSUE THREAD

**Issue by Yoko11111111** [MatrixTM/OutlookGen#5]
Hello i have proxy errors but i have the fomrat ip:port do i have to use another format or is it just not working anymore?

eGen>> Something is wrong :(
eGen>> 45.152.202.21:9026
eGen>> Something is wrong :(
eGen>> 193.23.245.202:8773
eGen>> Something is wrong :(
eGen>> 45.154.56.96:7114
eGen>> Something is wrong :(
eGen>> 45.87.240.83:8176
eGen>> Something is wrong :(
eGen>> 45.192.141.74:5111
eGen>> Something is wrong :(
eGen>> 23.236.255.208:7259
eGen>> Something is wrong :(
eGen>> 193.23.253.109:7681
eGen>> Something is wrong :(
eGen>> 154.95.0.208:6461
eGen>> Something is wrong :(
eGen>> 23.236.255.208:7259
eGen>> Something is wrong :(
eGen>> 37.35.42.207:8809
eGen>> Something is wrong :(
eGen>> 45.155.71.4:8593
eGen>> Something is wrong :(
eGen>> 186.179.17.134:7159
eGen>> Something is wrong :(
eGen>> 45.152.202.21:9026

**Comment by BlackSnowDot** [comment]
proxy problem
try with http https proxy

**Comment by Yoko11111111** [comment]
It is http

**Comment by Yoko11111111** [comment]
My Proxys work for sure because i have used some other tools too worked fine

**Comment by BlackSnowDot** [comment]
no, its okey i test it

**Comment by Yoko11111111** [comment]
Whats the problem then

**Comment by Yoko11111111** [comment]
![grafik](https://user-images.githubusercontent.com/108374464/195341235-1f0eb1f9-252c-4535-b023-f5a3c04ba84f.png)
No errors
