### ISSUE TITLE
"Something is wrong"

### ISSUE THREAD

**Issue by driv3n** [MatrixTM/OutlookGen#7]
I'm using the proxies from your auto update repo, but am still getting that error.

**Comment by BlackSnowDot** [comment]
[this proxies ](https://github.com/BlackSnowDot/proxylist-update-every-minute)not for generating email or something like that

**Comment by driv3n** [comment]
> [this proxies ](https://github.com/BlackSnowDot/proxylist-update-every-minute)not for generating email or something like that

Do you have any recommendations for proxies that are currently working for this project?

**Comment by BlackSnowDot** [comment]
i use [proxydocker](https://www.proxydocker.com/) google proxies

**Comment by driv3n** [comment]
I've tried with google and google HTTP-HTTPS, but no success and still same error. Any other changes or solutions i can try?

**Comment by bajwha2** [comment]
same issue with me I think I am also doing something wrong

**Comment by Yoko11111111** [comment]
> [this proxies ](https://github.com/BlackSnowDot/proxylist-update-every-minute)not for generating email or something like that

doesnt matter because your tool dont work
